### ISSUE TITLE
Pythonでのイルミナさん動作確認

### ISSUE THREAD

**Issue by efu-lotus** [Gllitter-bot/ilmina_bot#1]
test.pyが自分のPCから動作することを確認してみてくださいな。

**Comment by efu-lotus** [comment]
実行の確認が出来たら、test.pyはほぼ弄らずに残しておく感じで。
また新しくプログラムを用意します。

**Comment by yasutaka451** [comment]
`test.py`がどんな関数使ってるのかわからんから，`discord.py`の中身を見たいよねー
探してみるわ

**Comment by yasutaka451** [comment]
勘違いしてた
`discord`ってのはリポジトリというかディレクトリで，それをインストールしたのか
これの作成者が思ったよりも頭おかしい（褒め言葉）んで，完全にツールとして使う感じですね
`examples`にあるプログラムを読んでどんなことができるのか把握して，それに似た動作をちゃちゃっと実装する感じになる
以上のことをやっと理解しました

**Comment by efu-lotus** [comment]
です、説明不足だったかもですね。
最初のうちはexampleを参考に色々試してみるのがいいかも。
地道に学習してもいいんですけど、大変ですし。
