### ISSUE TITLE
新規プログラムファイルの作成

### ISSUE THREAD

**Issue by efu-lotus** [Gllitter-bot/ilmina_bot#2]
これに関してはこちらで済ませようかと思います。
ひとまずは、起動と終了のプログラムは必須として、おまけに簡単な返答ができるようにしたらプッシュしますね。
終了の部分を書いたことがないので、厳しそうでしたらその前にプッシュします。

**Comment by efu-lotus** [comment]
というわけで、
①起動と終了
②簡単な返答
の2つができるプログラムが書けたらひとまず完了とします。

**Comment by yasutaka451** [comment]
`test.py`でもその基本機能はあったんじゃなかったか？

起動と終了というのは，`!shutdown`みたいに操作してたアレのことですかね
確かに今あの機能は備わってないな
ちなみに，簡単な返答に関しては，文中にキーワードが存在してる時にも反応するように調整するって理解でおｋ？

**Comment by efu-lotus** [comment]
②の方はそのまま使おうかと思ってます。
問題なのは終了の方で、とりあえずは書けたけど問題のない処理なのかが微妙？
スマートじゃない、って意味合いです。
ひとまずプッシュしてみます。

**Comment by yasutaka451** [comment]
おけ
確認しました
この`!shutdown`ってのはあまりスマートじゃないの？
どのような不具合が想定されるのかわからんのでなんとも...

**Comment by yasutaka451** [comment]
ついでに言うと、編集するときにはこまめにブランチ切ってくれな！
