### ISSUE TITLE
トークンを勝手に置き換えてくれるプログラムを作る

### ISSUE THREAD

**Issue by yasutaka451** [Gllitter-bot/ilmina_bot#3]
正直，毎回動作確認の度にトークンを置換して，コミットするときにはまた置換するってのがだるいし，ミスも出てくると思う
ので，トークンを置き換えたファイルを`ilmina.py`として，俺らがいじるファイルを`ilmina_bub.py`として，実行するときに`ilmina_pub.py`から`ilmina.py`を作成するプログラムを作ろう
そんで，トークンの記述してある`ilmina.py`は`.gitignore`に入れとけばGitの管理から外れるはずなので

**Comment by efu-lotus** [comment]
なんとなく伝わりましたけど、こちら方法がさっぱりなので…。
調べればわかるかもですが。
